version: '3.7'
services:
  bigland.roads.api:
    image: nginx:alpine
    restart: always
    environment:
      - VIRTUAL_HOST=zbbg.localhost
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/common.nginx:/etc/nginx/conf.d/default.conf
    links:
      - zbbg.php

  zbbg.php:
    restart: always
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    env_file:
      - ./.env
    working_dir: /var/www/html
    volumes:
      - ./app/:/var/www/html
      - ./docker/php/conf.d/php-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ~/.ssh:/home/www-data/.ssh:ro
    links:
      - zbbg.mysql
    tty: true

  zbbg.mysql:
    image: mysql:8.0.29-debian
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/sql-dist/:/docker-entrypoint-initdb.d/
    expose:
      - 3306
    ports:
      - "8024:3306"

volumes:
  zbbg.data-mysql:
    external: true

networks:
  default:
    external:
      name: nginx-proxy