version: '3.7'
services:
  zbbg.php:
    restart: always
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    env_file:
      - ./.env
    working_dir: /var/www/html
    volumes:
      - ./app/:/var/www/html
      - ./docker/php/conf.d/php-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ~/.ssh:/home/www-data/.ssh:ro
    links:
      - zbbg.mysql
    tty: true

  zbbg.mysql:
    image: mysql:8.0.29-debian
    env_file:
      - ./.env
    restart: always
    volumes:
      - zbbg.data-mysql:/var/lib/mysql
      - ./docker/mysql/sql-dist/:/docker-entrypoint-initdb.d/
    expose:
      - 3306
    ports:
      - "8024:3306"

volumes:
  zbbg.data-mysql:
    external: true